// <auto-generated />
using System;
using LilsCareApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LilsCareApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240401044112_SeedMigration")]
    partial class SeedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.AddressDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Address Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Address");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("App User Id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Country");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("District");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("First Name Recipient");

                    b.Property<bool>("IsShippingToOffice")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Last Name Recipient");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Phone Number Recipient");

                    b.Property<string>("PostCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Post Code");

                    b.Property<int?>("ShippingOfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Town");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ShippingOfficeId");

                    b.ToTable("AddressDeliveries", t =>
                        {
                            t.HasComment("Address Delivery");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "bul. Vitosha",
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            Country = "Bulgaria",
                            District = "Sofia",
                            FirstName = "Ivan",
                            IsShippingToOffice = false,
                            LastName = "Ivanov",
                            PhoneNumber = "0888888888",
                            PostCode = "1000",
                            ShippingOfficeId = 1,
                            Town = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            Address = "bul. Vitosha",
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            Country = "Bulgaria",
                            District = "Sofia",
                            FirstName = "Petar",
                            IsShippingToOffice = false,
                            LastName = "Petrov",
                            PhoneNumber = "0888888888",
                            PostCode = "1000",
                            ShippingOfficeId = 2,
                            Town = "Sofia"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultAddressDeliveryId")
                        .HasColumnType("int")
                        .HasComment("Default Address Delivery Id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("First Name");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The image of user");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Last Name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultAddressDeliveryId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasComment("App User");
                        });

                    b.HasData(
                        new
                        {
                            Id = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69f1c7b2-d28d-4a56-9d26-67a270729390",
                            Email = "test@softuni.bg",
                            EmailConfirmed = true,
                            FirstName = "Test",
                            LastName = "Testov",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@SOFTUNI.BG",
                            NormalizedUserName = "TEST@SOFTUNI.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEO31/o23/qoSCsPPmGy5IIopzEeQn9ZHIaRlN88qPOAC+Nt8zFCQDHblD77vp3FdBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "187d17d7-1e7a-4c9b-8b25-943ebd46544c",
                            TwoFactorEnabled = false,
                            UserName = "test@softuni.bg"
                        },
                        new
                        {
                            Id = "45fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fff926c9-5a4a-4fde-88c1-985eb404bde2",
                            Email = "admin@mail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Adminov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFOuqKJhD5Thv4RR8bV2ouzYDsqKSKuQAlRDmoubKIZuPWZAd9i61m6dDmBHv02UBg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fa41b08c-661a-437d-a28c-67f01dc8dd1b",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.BagUser", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The user id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("The product id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("The quantity of the product that the user has added to his bag");

                    b.HasKey("AppUserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BagsUsers", t =>
                        {
                            t.HasComment("This table contains the products that the user has added to his bag");
                        });

                    b.HasData(
                        new
                        {
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            ProductId = 3,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The category's primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The category's name");

                    b.HasKey("Id");

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("The category of the product");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "за тяло"
                        },
                        new
                        {
                            Id = 2,
                            Name = "за суха кожа"
                        },
                        new
                        {
                            Id = 3,
                            Name = "за мазна кожа"
                        },
                        new
                        {
                            Id = 4,
                            Name = "за лице"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ImageProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The image id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The path of the image");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ImageProducts", t =>
                        {
                            t.HasComment("The image of the product");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/files/products/product-01-image-01.webp",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/files/products/product-01-image-02.webp",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "/files/products/product-01-image-03.webp",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "/files/products/product-01-image-04.webp",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "/files/products/product-02-image-01.webp",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "/files/products/product-02-image-02.webp",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "/files/products/product-02-image-03.webp",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "/files/products/product-02-image-04.webp",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "/files/products/product-02-image-05.webp",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "/files/products/product-03-image-01.webp",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "/files/products/product-03-image-02.webp",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "/files/products/product-03-image-03.webp",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "/files/products/product-03-image-04.webp",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "/files/products/product-03-image-05.webp",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "/files/products/product-04-image-01.webp",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "/files/products/product-04-image-02.webp",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "/files/products/product-04-image-03.webp",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "/files/products/product-04-image-04.webp",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "/files/products/product-05-image-01.webp",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "/files/products/product-05-image-02.webp",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "/files/products/product-05-image-03.webp",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "/files/products/product-05-image-04.webp",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "/files/products/product-06-image-01.webp",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "/files/products/product-06-image-02.webp",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "/files/products/product-06-image-03.webp",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "/files/products/product-06-image-04.webp",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 27,
                            ImagePath = "/files/products/product-06-image-05.webp",
                            ProductId = 6
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ImageReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The image id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The identifier of the author.");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The path of the image");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("The identifier of the product.");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "AuthorId");

                    b.ToTable("ImageReviews", t =>
                        {
                            t.HasComment("The image of the review");
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.MessageFromClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailForResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("MessagesFromClients");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDeliveryId")
                        .HasColumnType("int")
                        .HasComment("Address Delivery Id");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("App User Id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of Order Creating");

                    b.Property<DateTime?>("DateShipping")
                        .HasColumnType("datetime2")
                        .HasComment("Date of Shipping Creating");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Absolute Discount value");

                    b.Property<string>("NoteForDelivery")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Note for Delivery");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Order Number");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasComment("Payment Method Id");

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("int")
                        .HasComment("Promo Code Id");

                    b.Property<decimal>("ShippingPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Shipping Price");

                    b.Property<int>("StatusOrderId")
                        .HasColumnType("int")
                        .HasComment("Status of Order");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Sub Total");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Tracking Number of Order");

                    b.HasKey("Id");

                    b.HasIndex("AddressDeliveryId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PromoCodeId")
                        .IsUnique()
                        .HasFilter("[PromoCodeId] IS NOT NULL");

                    b.HasIndex("StatusOrderId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("Order");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDeliveryId = 1,
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            CreatedOn = new DateTime(2024, 4, 1, 4, 41, 9, 387, DateTimeKind.Utc).AddTicks(8029),
                            DateShipping = new DateTime(2024, 4, 1, 4, 41, 9, 387, DateTimeKind.Utc).AddTicks(9384),
                            Discount = 0m,
                            PaymentMethodId = 1,
                            ShippingPrice = 0m,
                            StatusOrderId = 1,
                            SubTotal = 0m,
                            Total = 0m,
                            TrackingNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            AddressDeliveryId = 2,
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            CreatedOn = new DateTime(2024, 4, 1, 4, 41, 9, 388, DateTimeKind.Utc).AddTicks(6693),
                            DateShipping = new DateTime(2024, 4, 1, 4, 41, 9, 388, DateTimeKind.Utc).AddTicks(6700),
                            Discount = 0m,
                            PaymentMethodId = 2,
                            ShippingPrice = 0m,
                            StatusOrderId = 2,
                            SubTotal = 0m,
                            Total = 0m,
                            TrackingNumber = "1234567890x"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Payment method id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Payment method type");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods", t =>
                        {
                            t.HasComment("Payment methods");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Наложен платеж"
                        },
                        new
                        {
                            Id = 2,
                            Type = "С карта"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Банков превод"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The product's primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("The product's description");

                    b.Property<string>("IngredientINCIs")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("The product ingredients INCI");

                    b.Property<string>("Ingredients")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("The product ingredients");

                    b.Property<bool>("IsShow")
                        .HasColumnType("bit")
                        .HasComment("Is the product show on online store");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The product's name");

                    b.Property<string>("Optional")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The optional property of product");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The product's price");

                    b.Property<string>("Purpose")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Properties of the product");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("The product's quantity");

                    b.Property<string>("ShippingCondition")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Condition of shipping the product");

                    b.HasKey("Id");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("The product model");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Нежен, изцяло натурален и ръчно изработен сух дезодорант. Подходящ за ежедневна употреба.\r\n\r\n \r\n\r\nБез парфюм и без етерични масла.\r\n\r\n \r\n\r\nВ нов твърд вариант за по-лесна употеба и нансяне дирктно.\r\n\r\n \r\n\r\nИли може да използвате стара опаковка от стик дезодорант, за да разтопите блокчето за удобна ежедневна употреба.\r\n\r\n \r\n\r\nСрежете блокчето на парченца и ги сложете в стик опаковка. Иползвайте микровълнова фурна на ниска температура и за картки интервали докато блокечето се разтопи. Оставете да изстине и стегне и готово!\r\n\r\n \r\n\r\nАко не разполагате с микровълнова фурна, може да го разтопите на водна баня в стик. Увийете плътно стик опковката със стреч фолио, за да не влиза вода в опковката и при продукта.\r\n\r\n \r\n\r\n100% натурален\r\n\r\n10 % от България\r\n\r\n78.4% био",
                            IngredientINCIs = "Cocos Nucifera (Coconut) Oil*, Tapioca Starch*, Butyrospermum Parkii (Shea) Butter*, Cera Alba (Beeswax), Glyceryl Stearate, Sodium Bicarbonate, Tocopherol (Vit E), Helianthus Annuus (Sunflower) Seed Oil* \r\n\r\n*Bio",
                            Ingredients = "Сухите съставки като био тапиока поддържат подмишниците сухи през деня.\r\n\r\nВитамин Е има антиоксидантен ефект.\r\n\r\nКокосово масло, масло от ший (карите) и пчелен восък.",
                            IsShow = true,
                            Name = "НАТУРАЛЕН СУХ ДЕЗОДОРАНТ",
                            Optional = "Тегло:  25 г.",
                            Price = 5.50m,
                            Purpose = "Вземете блокчето от кутийката и намажете подмишничите.\r\n\r\n \r\n\r\nИли внимателно го разтопете в опаковка за стик дезодорант за по-лесна и удобна ежедневна употреба.\r\n\r\n \r\n\r\nМоже да преизползвате стара опаковка от предишен дезодорант.\r\n\r\n \r\n\r\nСамо за външна употреба. Да се пази от достъп на деца. Не използвайте при алергия към някоя от съставките. Съхранявайте добре затворено на сухо място, защитено от пряка слънчева светлина.",
                            Quantity = 10,
                            ShippingCondition = "След като е посочен адрес за доставка или куриерски офис на Еконт или Спиди в полетата за адрес при поръчка, продуктите се опаковат внимателно в рециклирани картонена кутийка и хартиен пълнеж за уплътнение и се изпращат с доставка с преглед."
                        },
                        new
                        {
                            Id = 2,
                            Description = "Изцяло натурален и ръчно изработен балсам за устни, който носи усещане за уют и мекота. Създаден да е нежен и защитаващ.\r\n\r\n \r\n\r\nБио какаово масло\r\nЕстствен каков аромат\r\nКомбиниран с натурално масло от ванилия\r\nПчелен восък\r\n \r\n\r\nВ два варианта:\r\n\r\nЛек и блестящ прозрачен цвят\r\nИзцяло безцветен\r\n \r\n\r\nОбогатен с витамин Е и био масло от жожоба.\r\n\r\n \r\n\r\n100% натурален\r\n\r\n49% от България\r\n\r\n41% био",
                            IngredientINCIs = "Apricot Kernel Oil (масло от кайсиеви ядки), Theobroma Cacao Seed Butter (какаово масло)*, Copernicia Cerifera Cera (Карнаубски восък, веган)*, Simmondsia Chinensis Seed Oil (масло от жожоба)*, Helianthus Annuus Seed Oil (слънчогледово масло), Vanilla Planifolia Fruit Extract (екстракт от шушулки ванилия), Mica**, CI 77491 (Iron Oxide)**, Tocopherol (витамин E).\r\n*Био 49% **Минерални пигменти 1%",
                            Ingredients = "Какаовото масло* придава лек и естествен шоколадов аромат и предпазва устните.\r\n\r\n \r\n\r\nМаслото от жожоба* ги подхранва.\r\n\r\n \r\n\r\nПчелния восък* защитава устните, прави балсама траен както върху устните така и в тубичката да не свършва бързо. Придава усещане за възглванича и мекота върху устните.\r\n\r\n \r\n\r\nВитамин Е - натурален антиоксидант, който защитава от вредните влияния от околната среда.\r\n\r\n \r\n\r\n*Био 41% от състава",
                            IsShow = true,
                            Name = "БАЛСАМ ЗА УСТНИ С ЖОЖОБА, КАКАО И ПЧЕЛЕН ВОСЪК",
                            Optional = "Тегло:  5 г.",
                            Price = 4.00m,
                            Purpose = "Изцяло натурален, може да използвате винаги когато искате да подхраните и защитите устните си или просто да им придадете лек блясък за завършен вид на визията си.\r\n\r\n \r\n\r\nСамо за външна употреба. Да се пази от достъп на деца. Не използвайте при алергия към някоя от съставките. Съхранявайте със затворено капаче, на сухо място и защитено от пряка слънчева светлина.",
                            Quantity = 20,
                            ShippingCondition = "След като е посочен адрес за доставка или куриерски офис на Еконт или Спиди в полетата за адрес при поръчка, продуктите се опаковат внимателно в рециклирани картонена кутийка и хартиен пълнеж за уплътнение и се изпращат с доставка с преглед."
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IngredientINCIs = "Aqua (Вода), Rosa Canina Seed Oil* (масло от шипка, 10%) , Butyrospermum Parkii Butter* (масло от ший/карите), Glycerin (глицерин), Rosa Canina Fruit Extract (екстракт от шипка), Niacinamide (витамин B3), Cetearyl Olivate, Sorbitan Olivate (емулгатори), Sodium Hyaluronate (хиалуронова киселина), Tocopherol (витамин E), Helianthus Annuus (Слънчоглед) Seed Oil*, Sodium Benzoate, Potassium Sorbate (консерванти), Lactic Acid (млечна киселина, AHA, регулира pH на продукта).\r\n\r\n*Bio",
                            Ingredients = "Българско студено пресовано масло от шипка* - натурален източник на витамин А, подхранва и стимулура регенерирнето на кожата.\r\n\r\n \r\n\r\nЕкстракт от шипка - ботанически глицернов екстракт, който в този крем е чъдесна комбинация с маслото от шипка.\r\n\r\n \r\n\r\nМасло от ший* - Най-лекото и с най-нисък комедогенен рейтинг (0-2) от всички твърди масла. Това означава, че има ниска вероятност да запуши порите като скалата е от 0 до 5.\r\n\r\n \r\n\r\nВитамин B3 - ниацинамид - антиоксидант, който изравнява тена, регулира себума, помага худратацията и изглажда финни бръчки. Наистирна звучи неверояно, a е доакзрно.\r\n\r\n \r\n\r\nВитамин Е - има ефективо и естетвено антиоксидантно действие:  забвя стареенето като помага за възстановяването на кожата и я предпазва от свободните радикали и вредите от околната среда.\r\n\r\n \r\n\r\nРастителни глицерин и хиалурон - хумектанти - привличат водата и хидратират кожата. Ключова е концентрацията! Твърде много от тях могат да изсушат кожата, като започнат да издърпват влагата от по-дълбоките слоеве на кожата, когато въздуха е сух. Важен е баланса между вода и хумектанти в продукта.\r\n\r\n \r\n\r\n*Био",
                            IsShow = true,
                            Name = "ХИДРАТИРАЩ КРЕМ С ШИПКА И НИАЦИНАМИД",
                            Optional = "Тегло:  50 г.",
                            Price = 12.00m,
                            Purpose = "Нанесете върху суха или влажна кожа. Малко количество е достатъчно за цялото лице и шия. Използвайте 1-2 пъти дневно според необходимостта и сухотата на кожата.\r\n\r\n \r\n\r\nМоже да нансете върху влажна кожа, например след душ и измивен гел, за да заключите хидратацията.\r\n\r\n \r\n\r\nИли върхъ суха кожа, за да я защитите.\r\n\r\n \r\n\r\nНанасяйте върху добре почистена кожа с чисти ръце. Само за външна употреба. Да се пази от достъп на деца. Не използвайте при алергия към някоя от съставките. Съхранявайте добре затворено, на сухо място, защитено от пряка слънчева светлина.",
                            Quantity = 30,
                            ShippingCondition = "След като е посочен адрес за доставка или куриерски офис на Еконт или Спиди в полетата за адрес при поръчка, продуктите се опаковат внимателно в рециклирани картонена кутийка и хартиен пълнеж за уплътнение и се изпращат с доставка с преглед."
                        },
                        new
                        {
                            Id = 4,
                            Description = "Натурална мицеларна вода с два компонента. Разклатете преди употреба, за да се смесят двете фази. Идеална е за нежното отстраняване на грима в края на деня.\r\n\r\n \r\n\r\nИма двойно действие е като тоник за лице с екстракт от зелен чай и витамин Е.\r\n\r\n \r\n\r\nФаза 1 е изключително нежна. Има успокояващо и антиоксидантно действие благодарение на екстракта от зелен чай, сквален и пантенол (провитамин B3).\r\n\r\n \r\n\r\nФаза 2 е с био масло от жожоба и допринся за разтврянето на грима. Оставя кожата мека, подхранена и защитена.\r\n\r\n \r\n\r\nВ удобно шишенце с попма за лесно използване.\r\n\r\n \r\n\r\n100% натурална\r\n\r\n94% от България",
                            IngredientINCIs = "Aqua, Vitis Vinifera (Grape) Seed Oil, Camellia Sinensis (Green Tea) Leaf Extract,  Glycerin, Caprylic / Capric Triglycerides (Fractioned Coconut Oil), Simmondsia Chinensis (Jojoba) Seed Oil*, D-panthenol (Provitamin B5, plant-based), Coco Glucoside, Squalane, Sodium Surfactin, Tocopherol (Vit E), Helianthus Annuus (Sunflower) Seed Oil*, Potassium Sorbate, Sodium Benzoate, Benzyl Alcohol, Citric Acid, Citrus Paradisi (Grapefruit) Peel Oil, Limonene, Citral, Linalool.\r\n\r\n*Био",
                            Ingredients = "Екстракт от зелен чай - антиоксидантно и успокояващо действе, помага против появата на акне\r\n\r\n \r\n\r\nБио масло от Жожоба - помага за нежното разтваряне на грима и подхранва кожата\r\n\r\n \r\n\r\nВитамин Е - антиоксидант, успокоява раздразненията, бори се със свободните радикали и забавя стареенето на кожата\r\n\r\n \r\n\r\nПантенол - провитамин B5 - с растителен прозход. Хидратира и подхранва\r\n\r\n \r\n\r\nЕтерично масло грейпфрут - лек цитрусов аромат",
                            IsShow = true,
                            Name = "ДВУФАЗНА МИЦЕЛАРНА ВОДА ЗЕЛЕН ЧАЙ И ЖОЖОБА",
                            Optional = "Тегло:  100 мл.",
                            Price = 10.00m,
                            Purpose = "Разклаете преди употреба.\r\n\r\n \r\n\r\nМоже да използвате винаги, когато искате нежно да премахнете грима. Разклатете преди употреба и напоете памучно тампонче. Нежно притиснете към кожата, за да се намокри и да започне да разтваря грима. След това отстранете грима с леки движения от центъра на лицето към страните.\r\n\r\n \r\n\r\nСамо за външна употреба. Да се пази от достъп на деца. Не използвайте при алергия към някоя от съставките. Съхранявайте на сухо място, защитено от пряка слънчева светлина.",
                            Quantity = 0,
                            ShippingCondition = "След като е посочен адрес за доставка или куриерски офис на Еконт или Спиди в полетата за адрес при поръчка, продуктите се опаковат внимателно в рециклирани картонена кутийка и хартиен пълнеж за уплътнение и се изпращат с доставка с преглед."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Нежен, изцяло натурален и ръчно изработен дезодорант. Подходящ за ежедневна употреба. Етеричните масла от сладък портокал и евкалипт придват лек цитрусов аромат.\r\n\r\n \r\n\r\nИзбрахме точно тези етерични масла не само заради приятния аромат. Те притежават и по-добър антибактериален фект спрямо повечето етерични масла. Дори пречат на развитието и на различни видове гъбички. Това ознчава, че натурално може да намали лошата миризма при потене, която е причинена от бактериите под мишниците.\r\n\r\n \r\n\r\n100% натурален\r\n\r\n45.7 % от България\r\n\r\n44.5% био",
                            IngredientINCIs = "",
                            Ingredients = "Етеричните масла от сладък портокал и евкалипт придават свеж, леко ментов цитрусов аромат и имат антибактериален ефект.\r\n\r\n \r\n\r\nСухите съставки като био тапиока поддържат подмишниците сухи през деня.\r\n\r\n \r\n\r\nВитамин Е има антиоксидантен ефект.\r\n\r\n \r\n\r\nА цялата комбинация от съставки държи неприятните миризми далеч.",
                            IsShow = true,
                            Name = "НАТУРАЛЕН КРЕМ ДЕЗОДОРАНТ",
                            Optional = "Тегло:  50 г.",
                            Price = 8.50m,
                            Purpose = "Вземете на върха на пръстите много малко количесто (по-малко дори от грахово зрънце), леко го затоплете между пръстите и разнесете добре подмишниците.\r\n\r\n \r\n\r\nСамо за външна употреба. Да се пази от достъп на деца. Не използвайте при алергия към някоя от съставките. Съхранявайте добре затворено на сухо място, защитено от пряка слънчева светлина.",
                            Quantity = 10,
                            ShippingCondition = "След като е посочен адрес за доставка или куриерски офис на Еконт или Спиди в полетата за адрес при поръчка, продуктите се опаковат внимателно в рециклирани картонена кутийка и хартиен пълнеж за уплътнение и се изпращат с доставка с преглед."
                        },
                        new
                        {
                            Id = 6,
                            Description = "Създаден, за да се поглезите - с био масла от: шипка, ягодови семки, арган и жожба. Подхранва и защитава кожата. Запазва хидратацията като предпазва кожата от загуба на вода и я оставя мека и гладка.\r\n\r\n \r\n\r\nОбогатен с витамин Е за добър антиоксидантен ефект, който предпазва клетките от вредното въздействие отоколната среда, свободните радикали и оксидативни процеси. По този начин поддържа кожата млада и елстична.\r\n\r\n \r\n\r\nМаслото от шипка е натурален източник на витамин А. Аргановото масло и маслото от ягодови семки подхранват кожата, а маслото от жожоба съдържа натурални серамиди, подсилват кожната бариера и заздравяват връзките между клетките.\r\n\r\n\r\nНекомедогенен.\r\n\r\nНай-подходящ за суха кожа.\r\n\r\nИли като защита след по-изтощаваща рутина, напр. след химичен пилинг.\r\n\r\nПодхранва, заздравява и защитава кожната бариера.\r\n\r\n \r\n\r\nИзползвате няколко капки върху суха или влажна кожа (на пример след душ) или след хидратиращ лосион, за да 'заклчючите' хидратацията и да защитите кожата. \r\n\r\n \r\n\r\n100% натурален\r\n\r\n80% от България\r\n\r\n31% био",
                            IngredientINCIs = "Vitis Vinifera Seed Oil (масло от гроздови смеки), Rosa Canina Seed Oil (българско студенпресовно био масло от семената на шипка)*, Fragaria Ananassa Seed Oil (студенопресовано масло от семки на ягода), Argania Spinosa Kernel Oil (арганово масло)*, Simmondsia Chinensis Seed Oil (масло от жожоба)*, Tocopherol (Витамин E), Helianthus Annuus Seed Oil (Слънчогледово масло <0,2%) *,  Citrus Reticulata Oil (Етерично масло от мандарина) , Limonene**, Linalool**, Cananga Odorata flower Oil (Етерично масло от Иланг Иланф) *.\r\n*Био, 31%\r\n**Компоненети на етерични масла",
                            Ingredients = "Масло от шипка - помога ревитализирането на кожата \r\n\r\nМасло от ягодови семки - хидратира в дълбочина и има протививъзвпалителен ефект\r\n\r\nМасло от жожоба* - натурално съдържа над 95% серамиди, подхранва кожата и заздравява кожната бариера\r\n\r\nАрганово масло* - подхранва, защитава и подобрява хидратацията и еластичносттна на кожата\r\n\r\nМсла от мандарина и иланг-иланг* - придават лек, свеж и релаксиращ аромат, за да се насладите максимално на момента в грижа за кожата\r\n\r\nВитамин Е* - антиоксидант - успокоява раздразнената кожа и забавя страеенето като бори се със свободните радикали, UV уверждането и процесите на оксидация\r\n\r\n*Био",
                            IsShow = true,
                            Name = "ДВУФАЗНА МИЦЕЛАРНА ВОДА ЗЕЛЕН ЧАЙ И ЖОЖОБА",
                            Optional = "Тегло:  20 мл.",
                            Price = 10.00m,
                            Purpose = "Например след лек хидратиращ лосион, за да заключи хидратацията и полезните съставки.\r\n\r\nДиректно върху влажна кожа за по-добро абсорбиране и защита.\r\n\r\nИли върху суха кожа, за да предотврати трансепидеррмалната загуба на вода от кожата.\r\n\r\n \r\n\r\nПодходящ за защита на кожата в края на рутината. Комбинира се добре след ексфолиращи и/или хидратиращи продукти.\r\n\r\n \r\n\r\nСамо за външна употреба. Да се пази от достъп на деца. Не използвайте при алергия към някоя от съставките. Използвайте с чисти ръце и кожа. Съхранявайте добре затворено, на сухо място, защитено от пряка слънчева светлина.",
                            Quantity = 20,
                            ShippingCondition = "След като е посочен адрес за доставка или куриерски офис на Еконт или Спиди в полетата за адрес при поръчка, продуктите се опаковат внимателно в рециклирани картонена кутийка и хартиен пълнеж за уплътнение и се изпращат с доставка с преглед."
                        },
                        new
                        {
                            Id = 7,
                            IsShow = true,
                            Name = "Some name",
                            Price = 10.00m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("The product id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("The category id");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductsCategories", t =>
                        {
                            t.HasComment("Many to many relation between products and categories");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ProductOrder", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The image path of the product at the time of the order");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The price of the product at the time of the order");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("The quantity of the product in the order");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("ProductOrder", t =>
                        {
                            t.HasComment("Many to many relation between products and orders");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            OrderId = 1,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 1,
                            OrderId = 2,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 2,
                            OrderId = 1,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 3,
                            OrderId = 1,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 3,
                            OrderId = 2,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 4,
                            OrderId = 1,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 5,
                            OrderId = 2,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 6,
                            OrderId = 1,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 6,
                            OrderId = 2,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 7,
                            OrderId = 1,
                            ImagePath = "",
                            Price = 0m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Promo Code Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Owner of Promo Code");

                    b.Property<DateTime?>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Promo Code");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Discount of Total Price Order");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Expiration Date of Promo Code");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("PromoCodes", t =>
                        {
                            t.HasComment("Promo Code for one User");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            Code = "-10 % за регистрация",
                            Discount = 0.1m,
                            ExpirationDate = new DateTime(2025, 4, 1, 4, 41, 10, 237, DateTimeKind.Utc).AddTicks(6633)
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            Code = "-20 % отстъпка",
                            Discount = 0.2m,
                            ExpirationDate = new DateTime(2025, 4, 1, 4, 41, 10, 237, DateTimeKind.Utc).AddTicks(6643)
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("The identifier of the product.");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The identifier of the user that created the review.");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("The comment of the review.");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date when the review was created.");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasComment("The rating of the review.");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The title of the review.");

                    b.HasKey("ProductId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasComment("This class represents a review of a product.");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 2,
                            AuthorId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            Comment = "Great product, I love it!",
                            CreatedOn = new DateTime(2024, 4, 1, 7, 41, 10, 237, DateTimeKind.Local).AddTicks(6211),
                            Rating = 4,
                            Title = "Great product"
                        },
                        new
                        {
                            ProductId = 3,
                            AuthorId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            Comment = "Great product, I love it!",
                            CreatedOn = new DateTime(2024, 4, 1, 7, 41, 10, 237, DateTimeKind.Local).AddTicks(6272),
                            Rating = 3,
                            Title = "Great product"
                        },
                        new
                        {
                            ProductId = 4,
                            AuthorId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            Comment = "Great product, I love it!",
                            CreatedOn = new DateTime(2024, 4, 1, 7, 41, 10, 237, DateTimeKind.Local).AddTicks(6276),
                            Rating = 3,
                            Title = "Great product"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ShippingOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of shipping");

                    b.Property<int>("ShippingDuration")
                        .HasColumnType("int")
                        .HasComment("Duration of shipping");

                    b.Property<int?>("ShippingProviderId")
                        .HasColumnType("int")
                        .HasComment("Shipping Provider Id");

                    b.HasKey("Id");

                    b.HasIndex("ShippingProviderId");

                    b.ToTable("ShippingOffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sofia",
                            OfficeAddress = "bul. Vitosha 100",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Sofia",
                            OfficeAddress = "bul. Hristo Botev 20",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 1
                        },
                        new
                        {
                            Id = 3,
                            City = "Varna",
                            OfficeAddress = "bul. Vitosha 100",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 1
                        },
                        new
                        {
                            Id = 4,
                            City = "Burgas",
                            OfficeAddress = "bul. Vitosha 100",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 1
                        },
                        new
                        {
                            Id = 5,
                            City = "Ruse",
                            OfficeAddress = "bul. Vitosha 100",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 1
                        },
                        new
                        {
                            Id = 6,
                            City = "Sofia",
                            OfficeAddress = "bul. Vitosha 200",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 2
                        },
                        new
                        {
                            Id = 7,
                            City = "Sofia",
                            OfficeAddress = "bul. Hristo Botev 30",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 2
                        },
                        new
                        {
                            Id = 8,
                            City = "Sofia",
                            OfficeAddress = "bul. Bozveli 200",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 2
                        },
                        new
                        {
                            Id = 9,
                            City = "Burgas",
                            OfficeAddress = "bul. Vitosha 200",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 2
                        },
                        new
                        {
                            Id = 10,
                            City = "Ruse",
                            OfficeAddress = "bul. Vitosha 200",
                            Price = 5.00m,
                            ShippingDuration = 2,
                            ShippingProviderId = 2
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ShippingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier of shipping provider");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of shipping provider");

                    b.HasKey("Id");

                    b.ToTable("ShippingProviders", t =>
                        {
                            t.HasComment("Shipping providers");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Еконт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Спиди"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.StatusOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the status");

                    b.HasKey("Id");

                    b.ToTable("StatusOrders", t =>
                        {
                            t.HasComment("Status of the order");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Заявена"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отменена"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Изпратена"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Получена"
                        });
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.WishUser", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The user id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("The product id");

                    b.HasKey("AppUserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("WishesUsers", t =>
                        {
                            t.HasComment("This table contains the products that the user has added to his wish list");
                        });

                    b.HasData(
                        new
                        {
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            ProductId = 1
                        },
                        new
                        {
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            ProductId = 3
                        },
                        new
                        {
                            AppUserId = "85fbe739-6be0-429d-b44b-1ce6cf7eeef",
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.AddressDelivery", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany("AddressDelivery")
                        .HasForeignKey("AppUserId");

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.ShippingOffice", "ShippingOffice")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("ShippingOfficeId");

                    b.Navigation("AppUser");

                    b.Navigation("ShippingOffice");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.AppUser", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AddressDelivery", "DefaultAddressDelivery")
                        .WithMany()
                        .HasForeignKey("DefaultAddressDeliveryId");

                    b.Navigation("DefaultAddressDelivery");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.BagUser", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("BagsUsers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ImageProduct", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ImageReview", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Review", "Review")
                        .WithMany("Images")
                        .HasForeignKey("ProductId", "AuthorId");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.MessageFromClient", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AddressDelivery", "AddressDelivery")
                        .WithMany("Orders")
                        .HasForeignKey("AddressDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId");

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.PromoCode", "PromoCode")
                        .WithOne("Order")
                        .HasForeignKey("LilsCareApp.Infrastructure.Data.Models.Order", "PromoCodeId");

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.StatusOrder", "StatusOrder")
                        .WithMany("Orders")
                        .HasForeignKey("StatusOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressDelivery");

                    b.Navigation("AppUser");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PromoCode");

                    b.Navigation("StatusOrder");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ProductCategory", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("ProductsCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("ProductsCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ProductOrder", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.PromoCode", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany("PromoCodes")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ShippingOffice", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.ShippingProvider", "ShippingProvider")
                        .WithMany("ShippingOffices")
                        .HasForeignKey("ShippingProviderId");

                    b.Navigation("ShippingProvider");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Subscriber", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.WishUser", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("WishesUsers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LilsCareApp.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.AddressDelivery", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.AppUser", b =>
                {
                    b.Navigation("AddressDelivery");

                    b.Navigation("Orders");

                    b.Navigation("PromoCodes");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("ProductsCategories");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("ProductsOrders");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("BagsUsers");

                    b.Navigation("Images");

                    b.Navigation("ProductsCategories");

                    b.Navigation("ProductsOrders");

                    b.Navigation("Reviews");

                    b.Navigation("WishesUsers");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.PromoCode", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.Review", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ShippingOffice", b =>
                {
                    b.Navigation("DeliveryAddresses");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.ShippingProvider", b =>
                {
                    b.Navigation("ShippingOffices");
                });

            modelBuilder.Entity("LilsCareApp.Infrastructure.Data.Models.StatusOrder", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
